version: 0.0
os: linux 
files:
  - source: /
    destination: /home/ec2-user/apps/nodejsapps
hooks:
  ApplicationStart:
    - location: eShopProject/scripts/application_start.sh
      timeout: 300
      runas: ec2-user
